// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qy4ez6_cm_TzZDCO64LF8C-nG2mcqac',
    appId: '1:1090212787991:web:62075e11436a587dbb6952',
    messagingSenderId: '1090212787991',
    projectId: 'platformer-game-fe9ef',
    authDomain: 'platformer-game-fe9ef.firebaseapp.com',
    storageBucket: 'platformer-game-fe9ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ODnu6J_oPFXZrpd1QHjnwmvsFWUKLHE',
    appId: '1:1090212787991:android:d82fab6ed2b5c818bb6952',
    messagingSenderId: '1090212787991',
    projectId: 'platformer-game-fe9ef',
    storageBucket: 'platformer-game-fe9ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmxnWZ8TTcghE17RO1ERB3sxZU-kHHS50',
    appId: '1:1090212787991:ios:5974ac27e9dc6074bb6952',
    messagingSenderId: '1090212787991',
    projectId: 'platformer-game-fe9ef',
    storageBucket: 'platformer-game-fe9ef.appspot.com',
    iosBundleId: 'com.example.flamePlatformer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmxnWZ8TTcghE17RO1ERB3sxZU-kHHS50',
    appId: '1:1090212787991:ios:5974ac27e9dc6074bb6952',
    messagingSenderId: '1090212787991',
    projectId: 'platformer-game-fe9ef',
    storageBucket: 'platformer-game-fe9ef.appspot.com',
    iosBundleId: 'com.example.flamePlatformer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qy4ez6_cm_TzZDCO64LF8C-nG2mcqac',
    appId: '1:1090212787991:web:1194ac0b32c8a1ccbb6952',
    messagingSenderId: '1090212787991',
    projectId: 'platformer-game-fe9ef',
    authDomain: 'platformer-game-fe9ef.firebaseapp.com',
    storageBucket: 'platformer-game-fe9ef.appspot.com',
  );

}